MTL       = ../mtl
CHDRS     = $(wildcard *.h) $(wildcard $(MTL)/*.h)
EXEC      = minisatid
CFLAGS    = -I$(MTL) -I/export/home1/NoCsBack/dtai/broes/include -Wall -ffloat-store
LFLAGS    = -lz

include ../mtl/template.mk
