#!/bin/bash
#input: folder to start in
#Go over all files and replace the following macros

CURRENTLY USED LICENSES:
# Copyright 2007-2011 Katholieke Universiteit Leuven
# Use of this software is governed by the GNU LGPLv3.0 license
# Written by Broes De Cat and Maarten Mariën, K.U.Leuven, Departement
# Computerwetenschappen, Celestijnenlaan 200A, B-3001 Leuven, Belgium

/*
 * Copyright 2007-2011 Katholieke Universiteit Leuven
 *
 * Use of this software is governed by the GNU LGPLv3.0 license
 *
 * Written by Broes De Cat and Maarten Mariën, K.U.Leuven, Departement
 * Computerwetenschappen, Celestijnenlaan 200A, B-3001 Leuven, Belgium
 */
 
 
 

#C/c++/java comment style
STARTCOMM="/*\r"
COPYRIGHT=" * Copyright 2007-2011 Katholieke Universiteit Leuven\r"
LINE=" *\r"
LICENSE=" * Use of this software is governed by the GNU LGPLv3.0 license\r"
WRITTEN=" * Written by Broes De Cat and Maarten Mariën, K.U.Leuven, Departement\r"
ADDRESS=" * Computerwetenschappen, Celestijnenlaan 200A, B-3001 Leuven, Belgium\r"
ENDCOMM=" */\r"

HIGHPROGLICENSE="$STARTCOMM$COPYRIGHT$LINE$LICENSE$LINE$WRITTEN$ADDRESS$ENDCOMM"
ESCAPEDHIGHPROGLICENSE=$(echo "$HIGHPROGLICENSE" | sed 's/\//\\&/g')

HIGHPROGPLACEHOLDER="//LICENSEPLACEHOLDER"
ESCAPEDHIGHPROGPLACEHOLDER=$(echo "$HIGHPROGPLACEHOLDER" | sed 's/\(\/\|\\\|&\)/\\&/g')

for a in `grep -lr "$HIGHPROGPLACEHOLDER" $1`
do
	sed -i "s/$ESCAPEDHIGHPROGPLACEHOLDER/$ESCAPEDHIGHPROGLICENSE/g" "$a"
done

#bash, makefile style comments #
STARTCOMM=""
COPYRIGHT="# Copyright 2007-2011 Katholieke Universiteit Leuven\r"
LINE=""
LICENSE="# Use of this software is governed by the GNU LGPLv3.0 license\r"
WRITTEN="# Written by Broes De Cat and Maarten Mariën, K.U.Leuven, Departement\r"
ADDRESS="# Computerwetenschappen, Celestijnenlaan 200A, B-3001 Leuven, Belgium\r"
ENDCOMM=""

LOWPROGLICENSE="$STARTCOMM$COPYRIGHT$LINE$LICENSE$LINE$WRITTEN$ADDRESS$ENDCOMM"
ESCAPEDLOWPROGLICENSE=$(echo "$LOWPROGLICENSE" | sed 's/\//\\&/g')

LOWPROGPLACEHOLDER="#LICENSEPLACEHOLDER"
ESCAPEDLOWPROGPLACEHOLDER=$(echo "$LOWPROGPLACEHOLDER" | sed 's/\(\/\|\\\|&\)/\\&/g')

for a in `grep -lr "$LOWPROGPLACEHOLDER" $1`
do
	sed -i "s/$ESCAPEDLOWPROGPLACEHOLDER/$ESCAPEDLOWPROGLICENSE/g" "$a"
done