#!/bin/bash
cd ../
autoreconf --force --install
mkdir buildrelease resources

cd resources
mkdir unix win mac
cd unix
mkdir 32 64
cd ../win
mkdir 32 64
cd ../mac
mkdir 32
cd ../../

cd buildrelease
mkdir unix32 unix64 win32 win64

cd unix32
../../configure --enable-build=release --enable-sat=new --enable-perftools=no --enable-gmp=no --enable-bits=32
make LDFLAGS=-all-static CXXFLAGS="-D DATADIR=\\\".\\\""
cp src/minisatid ../../resources/unix/32
cd ../

cd unix64
../../configure --enable-build=release --enable-sat=new --enable-perftools=no --enable-gmp=no --enable-bits=64
make LDFLAGS=-all-static CXXFLAGS="-D DATADIR=\\\".\\\""
cp src/minisatid ../../resources/unix/64
cd ../

cd win32
../../configure --enable-build=release --enable-sat=new --enable-perftools=no --enable-gmp=no --enable-bits=32 RANLIB=/home/broes/Desktop/mingw32/bin/i686-w64-mingw32-ranlib
make LDFLAGS=-all-static CXXFLAGS="-D DATADIR=\\\".\\\"" CXX=/home/broes/Desktop/mingw32/bin/i686-w64-mingw32-g++
cp src/minisatid ../../resources/win/32/minisatid.exe
cd ../

cd win64
../../configure --enable-build=release --enable-sat=new --enable-perftools=no --enable-gmp=no --enable-bits=64 RANLIB=/home/broes/Desktop/mingw64/bin/x86_64-w64-mingw32-ranlib
make LDFLAGS=-all-static CXXFLAGS="-D DATADIR=\\\".\\\"" CXX=/home/broes/Desktop/mingw64/bin/x86_64-w64-mingw32-g++
cp src/minisatid ../../resources/win/64/minisatid.exe
cd ../
