#Works under the assumption than when gecode is installed at least the kernel component exists
# Look for the header file
find_path(GECODE_INCLUDE_DIR PATHS ${GECODE_DIR} NAMES gecode/kernel.hh)
find_file(GECODE_CONFIG PATHS ${GECODE_DIR} gecode/support/config.hpp)
# Look for the library
find_library(GECODE_LIBRARY PATHS ${GECODE_DIR} NAMES gecodekernel)
find_library(GECODE_SUPPORT_LIBRARY PATHS ${GECODE_DIR} NAMES gecodesupport)

if(GECODE_CONFIG)
	file(STRINGS ${GECODE_CONFIG} GECODE_LINE_VERSION REGEX "^#define GECODE_VERSION .*")
	string(REGEX MATCH "[0-9].[0-9].[0-9]" GECODE_VERSION ${GECODE_LINE_VERSION})
endif()

if(GECODE_INCLUDE_DIR AND GECODE_LIBRARY AND GECODE_SUPPORT_LIBRARY)
	set(GECODE_FOUND Yes)
endif()

if(GECODE_FOUND)
	set(Gecode_LIBRARIES ${GECODE_LIBRARY} ${GECODE_SUPPORT_LIBRARY})
	set(Gecode_INCLUDE_DIRS ${GECODE_INCLUDE_DIR})
	find_library(GECODE_DRIVER_LIBRARY PATHS ${GECODE_DIR} gecodedriver)
	if(GECODE_DRIVER_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_DRIVER_LIBRARY})
	endif()
	find_library(GECODE_FZ_LIBRARY PATHS ${GECODE_DIR} gecodeflatzinc)
	if(GECODE_FZ_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_FZ_LIBRARY})
	endif()
	find_library(GECODE_GIST_LIBRARY PATHS ${GECODE_DIR} gecodegist)
	if(GECODE_GIST_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_GIST_LIBRARY})
	endif()
	find_library(GECODE_GRAPH_LIBRARY PATHS ${GECODE_DIR} gecodegraph)
	if(GECODE_GRAPH_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_GRAPH_LIBRARY})
	endif()
	find_library(GECODE_INT_LIBRARY PATHS ${GECODE_DIR} gecodeint)
	if(GECODE_INT_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_INT_LIBRARY})
	endif()
	find_library(GECODE_MM_LIBRARY PATHS ${GECODE_DIR} gecodeminimodel)
	if(GECODE_MM_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_MM_LIBRARY})
	endif()
	find_library(GECODE_SCHEDULING_LIBRARY PATHS ${GECODE_DIR} gecodescheduling)
	if(GECODE_SCHEDULING_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_SCHEDULING_LIBRARY})
	endif()
	find_library(GECODE_SEARCH_LIBRARY PATHS ${GECODE_DIR} gecodesearch)
	if(GECODE_SEARCH_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_SEARCH_LIBRARY})
	endif()
	find_library(GECODE_SET_LIBRARY PATHS ${GECODE_DIR} gecodeset)
	if(GECODE_SET_LIBRARY)
		list(APPEND Gecode_LIBRARIES ${GECODE_SET_LIBRARY})
	endif()
endif()
